CREATE OR REPLACE TABLE BIGDATA_GITHUB.ANALYTICS.YEARLY_COMMIT_SUMMARY AS
SELECT 
    EXTRACT(YEAR FROM TO_DATE(commit_at)) AS year,
    COUNT(*) AS total_commits
FROM BIGDATA_GITHUB.RAW.COMMIT_LIST_TABLE
WHERE commit_at IS NOT NULL
  AND EXTRACT(YEAR FROM TO_DATE(commit_at)) BETWEEN 2008 AND 2019
GROUP BY year
ORDER BY year;
